version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./dobr:/usr/share/nginx/html/livemzhrn:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro